modLoader="kotlinforforge"
loaderVersion="${deps.kff}"
license="${mod.license}"
issueTrackerURL="${mod.issues_url}"

[[mods]]
modId="${mod.id}"
version="${mod.version}+${env.minecraft}-${env.loader}"
displayName="${mod.name}"
updateJSONURL="${mod.forge_updates_url}"
displayURL="${mod.homepage_url}"
logoFile="icon.png"
authors="${mod.authors}"
description='''${mod.description}'''

#[[mixins]]
#config="${mod.id}.mixins.json"

#[[accessTransformers]]
#file="META-INF/accesstransformer.cfg"

[[dependencies.${mod.id}]]
modId="forge"
versionRange="${deps.forge}"
mandatory=true

[[dependencies.${mod.id}]]
modId="waystones"
versionRange="${deps.waystones}"
mandatory=true

[[dependencies.${mod.id}]]
modId="balm"
versionRange="${deps.balm}"
mandatory=true

#? if yacl {
[[dependencies.${mod.id}]]
modId="yet_another_config_lib_v3"
versionRange="${deps.yacl}"
mandatory=true
#? }
