modLoader="kotlinforforge"
loaderVersion="${deps.kff}"
license="${mod.license}"
issueTrackerURL="${mod.issues_url}"

[[mods]]
modId="${mod.id}"
version="${mod.version}"
displayName="${mod.name}"
updateJSONURL="${mod.forge_updates_url}"
displayURL="${mod.homepage_url}"
logoFile="icon.png"
authors="${mod.authors}"
description='''${mod.description}'''

#[[mixins]]
#config="${mod.id}.mixins.json"

#[[accessTransformers]]
#file="META-INF/accesstransformer.cfg"

[[dependencies.${mod.id}]]
modId="neoforge"
type="required"
versionRange="${deps.neoforge}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod.id}]]
modId="minecraft"
type="required"
versionRange="${deps.minecraft}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod.id}]]
modId="waystones"
type="required"
versionRange="${deps.waystones}"

[[dependencies.${mod.id}]]
modId="balm"
type="required"
versionRange="${deps.balm}"

#? if yacl {
[[dependencies.${mod.id}]]
modId="yet_another_config_lib_v3"
type="required"
versionRange="${deps.yacl}"
ordering="NONE"
side="CLIENT"
#? }